version: "2"
services:
  db:
    image: mdillon/postgis:9.6
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_spoon
      POSTGRES_DB: shopping_cart
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=shopping_cart.settings
    volumes:
      - ./:/code
    env_file:
      - .env
    working_dir: /code
    depends_on:
      - db
    ports:
      - '8000:8000'
    command: bash -c "pip install -r requirements.txt && invoke run-local"
