version: "2"
services:
  db:
    image: mdillon/postgis:9.6
    expose:
      - 5432
    environment:
      POSTGRES_USER: shopping_cart
      POSTGRES_PASSWORD: wTAAC9rwTsfIR
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=shopping_cart.settings
    volumes:
      - ./:/code
    env_file:
      - .env
    working_dir: /code
    depends_on:
      - db
    ports:
      - '8000:8000'
    command: /bin/bash -c "pip install --upgrade pip && pip install -r requirements.txt && exec invoke run-local"
